// svelte/4/SafeCard.svelte
<!--
  SafeCard — Svelte 5 card component.
  Implements card contract from safecontracts.
  Outputs data-* attributes for intent. No hardcoded CSS.
-->
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
</script>

<div
  data-component="card"
  data-variant={config.metadata.variant}
  data-surface={config.metadata.surface}
  data-spacing={config.metadata.spacing}
  data-radius={config.metadata.radius}
  data-density={config.metadata.density}
>
  {#if config.metadata.header}<div data-role="header">{config.metadata.header}</div>{/if}
  <slot />
</div>

// angular/22/SafeCard.ts
/**
 * SafeCard — Angular card component.
 * Implements card contract from safecontracts.
 * Outputs data-* attributes for intent. No hardcoded CSS.
 */
import { Component, Input } from '@angular/core';
import { NgIf } from '@angular/common';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';

@Component({
  selector: 'safe-card',
  standalone: true,
  imports: [NgIf],
  template: `
    <div *ngIf="config.metadata.header" data-role="header">{{ config.metadata.header }}</div>
    <ng-content></ng-content>
  `,
  host: {
    '[attr.data-component]': "'card'",
    '[attr.data-variant]': 'config.metadata.variant',
    '[attr.data-surface]': 'config.metadata.surface',
    '[attr.data-spacing]': 'config.metadata.spacing',
    '[attr.data-radius]': 'config.metadata.radius',
    '[attr.data-density]': 'config.metadata.density'
  }
})
export class SafeCardComponent {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
}
