// svelte/4/SafeNav.svelte
<!--
  SafeNav — Svelte 4 nav component.
  Outputs data-* attributes for intent. No hardcoded CSS.
-->
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
</script>

<div
  data-component="nav"
  data-nav-style={config.metadata.navStyle}
>
  {#if config.metadata.title}<div data-nav-header><div data-nav-logo>{config.metadata.title?.charAt(0)}</div><div data-nav-title>{config.metadata.title}</div></div>{/if}
    <nav data-nav-main><slot /></nav>
</div>

// angular/21/SafeNav.ts
/**
 * SafeNav — Angular nav component.
 * Implements nav contract from safecontracts.
 * Outputs data-* attributes for intent. No hardcoded CSS.
 */
import { Component, Input } from '@angular/core';
import { NgIf } from '@angular/common';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';

@Component({
  selector: 'safe-nav',
  standalone: true,
  imports: [NgIf],
  template: `
    <div *ngIf="config.metadata.title" data-nav-header>
      <div data-nav-logo>{{ config.metadata.title?.charAt(0) }}</div>
      <div data-nav-title>{{ config.metadata.title }}</div>
    </div>
    <nav data-nav-main><ng-content></ng-content></nav>
  `,
  host: {
    '[attr.data-component]': "'nav'",
    '[attr.data-nav-style]': 'config.metadata.navStyle'
  }
})
export class SafeNavComponent {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
}
