// svelte/4/SafeTabs.svelte
<!--
  SafeTabs — Svelte 4 tabbed panel navigation.
  Renders via shared-mapping tabs builder (./tabs) — identical across
  frameworks. Structure + data-* only.
-->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { createSafeTabs } from './tabs';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  onMount(() => {
    root = createSafeTabs(container, config, onEvent);
  });

  onDestroy(() => {
    root?.remove();
    root = null;
  });
</script>

<div bind:this={container}></div>

// angular/21/SafeTabs.ts
/**
 * SafeTabs — Angular tabbed panel navigation.
 * Renders via shared-mapping tabs builder (./tabs) — identical across
 * frameworks. Structure + data-* only.
 */
import { Component, Input, ElementRef, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { createSafeTabs } from './tabs';

@Component({
  selector: 'safe-tabs',
  standalone: true,
  template: `<div #tabsContainer></div>`
})
export class SafeTabsComponent implements AfterViewInit, OnDestroy {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
  @ViewChild('tabsContainer') containerRef!: ElementRef<HTMLElement>;
  private root: HTMLElement | null = null;

  ngAfterViewInit() {
    this.root = createSafeTabs(this.containerRef.nativeElement, this.config, this.onEvent);
  }

  ngOnDestroy() {
    this.root?.remove();
    this.root = null;
  }
}
