// svelte/4/SafeList.svelte
<!--
  SafeList — Svelte 4 flexible list.
  Renders via shared-mapping list builder (./list) — identical across
  frameworks (figma Atom List Specs). Structure + data-* only.
-->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { createSafeList } from './list';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  onMount(() => {
    root = createSafeList(container, config, onEvent);
  });

  onDestroy(() => {
    root?.remove();
    root = null;
  });
</script>

<div bind:this={container}></div>

// angular/21/SafeList.ts
/**
 * SafeList — Angular flexible list.
 * Renders via shared-mapping list builder (./list) — identical across
 * frameworks (figma Atom List Specs). Structure + data-* only.
 */
import { Component, Input, ElementRef, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { createSafeList } from './list';

@Component({
  selector: 'safe-list',
  standalone: true,
  template: `<div #listContainer></div>`
})
export class SafeListComponent implements AfterViewInit, OnDestroy {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
  @ViewChild('listContainer') containerRef!: ElementRef<HTMLElement>;
  private root: HTMLElement | null = null;

  ngAfterViewInit() {
    this.root = createSafeList(this.containerRef.nativeElement, this.config, this.onEvent);
  }

  ngOnDestroy() {
    this.root?.remove();
    this.root = null;
  }
}
