// svelte/4/SafeLayout.svelte
<!--
  SafeLayout — Svelte 4 named-region composition.
  Renders via shared-mapping layout builder (./layout) — identical across
  frameworks. Structure + data-* only.
-->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { createSafeLayout } from './layout';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  onMount(() => {
    root = createSafeLayout(container, config, onEvent);
  });

  onDestroy(() => {
    root?.remove();
    root = null;
  });
</script>

<div bind:this={container}></div>

// angular/21/SafeLayout.ts
/**
 * SafeLayout — Angular named-region composition.
 * Renders via shared-mapping layout builder (./layout) — identical across
 * frameworks. Structure + data-* only.
 */
import { Component, Input, ElementRef, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { createSafeLayout } from './layout';

@Component({
  selector: 'safe-layout',
  standalone: true,
  template: `<div #layoutContainer></div>`
})
export class SafeLayoutComponent implements AfterViewInit, OnDestroy {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
  @ViewChild('layoutContainer') containerRef!: ElementRef<HTMLElement>;
  private root: HTMLElement | null = null;

  ngAfterViewInit() {
    this.root = createSafeLayout(this.containerRef.nativeElement, this.config, this.onEvent);
  }

  ngOnDestroy() {
    this.root?.remove();
    this.root = null;
  }
}
