// vue/3/SafeDispatch.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { buildComponent } from '../../utils/render';
const props = defineProps<{ config: ConfigBase; onEvent?: OnSafeEvent }>();
const containerRef = ref<HTMLElement | null>(null);
let root: HTMLElement | null = null;
onMounted(() => { if (containerRef.value) { root = buildComponent(props.config, props.onEvent); containerRef.value.appendChild(root); } });
onBeforeUnmount(() => { root?.remove(); root = null; });
</script>
<template><div ref="containerRef"></div></template>

// angular/21/SafeDispatch.ts
import { Component, Input, ElementRef, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { buildComponent } from '../../utils/render';
@Component({ selector: 'safe-dispatch', standalone: true, template: `<div #dispatchContainer></div>` })
export class SafeDispatchComponent implements AfterViewInit, OnDestroy {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
  @ViewChild('dispatchContainer') containerRef!: ElementRef<HTMLElement>;
  private root: HTMLElement | null = null;
  ngAfterViewInit() { this.root = buildComponent(this.config, this.onEvent); this.containerRef.nativeElement.appendChild(this.root); }
  ngOnDestroy() { this.root?.remove(); this.root = null; }
}
