// react/19/SafeSkillUp.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { buildComponent } from "../../utils/render";
interface SafeSkillUpProps { config: ConfigBase; onEvent?: OnSafeEvent; }
export function SafeSkillUp({ config, onEvent }: SafeSkillUpProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const c = containerRef.current; if (!c) return; c.innerHTML = ""; const r = buildComponent(config, onEvent); c.appendChild(r); return () => { r.remove(); }; }, [config, onEvent]);
  return <div ref={containerRef} />;
}

// angular/21/SafeSkillUp.ts
import { Component, Input, ElementRef, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { buildComponent } from '../../utils/render';
@Component({ selector: 'safe-skillup', standalone: true, template: `<div #skillupContainer></div>` })
export class SafeSkillUpComponent implements AfterViewInit, OnDestroy {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
  @ViewChild('skillupContainer') containerRef!: ElementRef<HTMLElement>;
  private root: HTMLElement | null = null;
  ngAfterViewInit() { this.root = buildComponent(this.config, this.onEvent); this.containerRef.nativeElement.appendChild(this.root); }
  ngOnDestroy() { this.root?.remove(); this.root = null; }
}
