// svelte/5/SafeRenderer.svelte
<script lang="ts">
  /**
   * SafeRenderer (svelte/5) — mechanical translator of the contract's
   * RenderPlan. Same walk as every framework (buildRenderPlan in
   * safecontracts); svelte 5 runes translation.
   */
  import SafeRenderer from "./SafeRenderer.svelte";
  import type { ConfigBase, OnSafeEvent, RenderPlan } from "safecontracts";
  import { buildRenderPlan, stampHandler } from "safecontracts";
  import SafeCard from "./SafeCard.svelte";
  import SafeButton from "./SafeButton.svelte";
  import SafeTable from "./SafeTable.svelte";
  import SafeTree from "./SafeTree.svelte";
  import SafeSheet from "./SafeSheet.svelte";
  import SafeChart from "./SafeChart.svelte";
  import SafeHeatmap from "./SafeHeatmap.svelte";
  import SafeGauge from "./SafeGauge.svelte";
  import SafeFunnel from "./SafeFunnel.svelte";
  import SafeFlow from "./SafeFlow.svelte";
  import SafeHierarchy from "./SafeHierarchy.svelte";
  import SafeTimeline from "./SafeTimeline.svelte";
  import SafeMap from "./SafeMap.svelte";
  import SafeCalendar from "./SafeCalendar.svelte";
  import SafeToggle from "./SafeToggle.svelte";
  import SafeWeek from "./SafeWeek.svelte";
  import SafeChat from "./SafeChat.svelte";
  import SafeTabs from "./SafeTabs.svelte";
  import SafeCallout from "./SafeCallout.svelte";
  import SafeDragDrop from "./SafeDragDrop.svelte";
  import SafeGrid from "./SafeGrid.svelte";
  import SafeInput from "./SafeInput.svelte";
  import SafeList from "./SafeList.svelte";
  import SafePicker from "./SafePicker.svelte";
  import SafeNav from "./SafeNav.svelte";

  const LEAVES: Record<string, any> = {
    card: SafeCard, button: SafeButton, table: SafeTable, tree: SafeTree,
    sheet: SafeSheet, chart: SafeChart, heatmap: SafeHeatmap, gauge: SafeGauge,
    funnel: SafeFunnel, flow: SafeFlow, hierarchy: SafeHierarchy,
    timeline: SafeTimeline, map: SafeMap, calendar: SafeCalendar,
    toggle: SafeToggle, week: SafeWeek, chat: SafeChat, tabs: SafeTabs,
    callout: SafeCallout, "drag-drop": SafeDragDrop, grid: SafeGrid,
    input: SafeInput, list: SafeList, picker: SafePicker, nav: SafeNav,
  };
  const KNOWN = new Set([...Object.keys(LEAVES), "layout", "columns"]);

  let { config, plan, onEvent }: { config?: ConfigBase; plan?: RenderPlan; onEvent?: OnSafeEvent } = $props();

  const p: RenderPlan = $derived(plan ?? buildRenderPlan(config!, KNOWN));
  const stamped: OnSafeEvent | undefined = $derived(
    onEvent ? (event) => onEvent!(stampHandler(event, p.handler)) : undefined
  );
  const columns: string = $derived((p.config.metadata?.columns as string) ?? "1fr");
</script>

{#if p.kind === "unknown"}
  <div data-component="unknown" style="padding: var(--sd-space-md); color: var(--sd-text-dim)">
    Unknown component: {p.component}
  </div>
{:else if p.component === "layout"}
  <div data-component="layout" data-variant={p.config.metadata?.variant} style="display:grid; grid-template-columns:{columns}; min-height:100vh">
    {#each p.children as c (c.key)}
      <div data-region={c.key}><SafeRenderer plan={c.plan} {onEvent} /></div>
    {/each}
  </div>
{:else if p.component === "columns"}
  <div data-component="columns" style="display:grid; grid-template-columns:{columns}; gap:var(--sd-space-md)">
    {#each p.children as c (c.key)}
      <div data-child={c.key}><SafeRenderer plan={c.plan} {onEvent} /></div>
    {/each}
  </div>
{:else}
  {@const Impl = LEAVES[p.component]}
  <Impl config={p.config} onEvent={stamped} />
  {#if p.childMode !== "component" && p.children.length > 0}
    <div data-role="children">
      {#each p.children as c (c.key)}
        <SafeRenderer plan={c.plan} {onEvent} />
      {/each}
    </div>
  {/if}
{/if}

// angular/21/SafeRenderer.ts
/**
 * SafeRenderer (angular/21) — mechanical translator of the contract's
 * RenderPlan. Same walk as every framework; Angular standalone component
 * with NgComponentOutlet dispatch and template recursion.
 */
import { Component, Input, OnChanges } from "@angular/core";
import { NgFor, NgIf, NgComponentOutlet, NgStyle } from "@angular/common";
import type { ConfigBase, OnSafeEvent, RenderPlan } from "safecontracts";
import { buildRenderPlan, stampHandler } from "safecontracts";
import { SafeCardComponent } from "./SafeCard";
import { SafeButtonComponent } from "./SafeButton";
import { SafeTableComponent } from "./SafeTable";
import { SafeTreeComponent } from "./SafeTree";
import { SafeSheetComponent } from "./SafeSheet";
import { SafeChartComponent } from "./SafeChart";
import { SafeHeatmapComponent } from "./SafeHeatmap";
import { SafeGaugeComponent } from "./SafeGauge";
import { SafeFunnelComponent } from "./SafeFunnel";
import { SafeFlowComponent } from "./SafeFlow";
import { SafeHierarchyComponent } from "./SafeHierarchy";
import { SafeTimelineComponent } from "./SafeTimeline";
import { SafeMapComponent } from "./SafeMap";
import { SafeCalendarComponent } from "./SafeCalendar";
import { SafeToggleComponent } from "./SafeToggle";
import { SafeWeekComponent } from "./SafeWeek";
import { SafeChatComponent } from "./SafeChat";
import { SafeTabsComponent } from "./SafeTabs";
import { SafeCalloutComponent } from "./SafeCallout";
import { SafeDragDropComponent } from "./SafeDragDrop";
import { SafeGridComponent } from "./SafeGrid";
import { SafeInputComponent } from "./SafeInput";
import { SafeListComponent } from "./SafeList";
import { SafePickerComponent } from "./SafePicker";
import { SafeNavComponent } from "./SafeNav";

const LEAVES: Record<string, any> = {
  card: SafeCardComponent, button: SafeButtonComponent, table: SafeTableComponent,
  tree: SafeTreeComponent, sheet: SafeSheetComponent, chart: SafeChartComponent,
  heatmap: SafeHeatmapComponent, gauge: SafeGaugeComponent, funnel: SafeFunnelComponent,
  flow: SafeFlowComponent, hierarchy: SafeHierarchyComponent, timeline: SafeTimelineComponent,
  map: SafeMapComponent, calendar: SafeCalendarComponent, toggle: SafeToggleComponent,
  week: SafeWeekComponent, chat: SafeChatComponent, tabs: SafeTabsComponent,
  callout: SafeCalloutComponent, "drag-drop": SafeDragDropComponent, grid: SafeGridComponent,
  input: SafeInputComponent, list: SafeListComponent, picker: SafePickerComponent,
  nav: SafeNavComponent,
};
const KNOWN = new Set([...Object.keys(LEAVES), "layout", "columns"]);

@Component({
  selector: "safe-renderer",
  standalone: true,
  imports: [NgFor, NgIf, NgComponentOutlet, NgStyle],
  template: `
    <div *ngIf="p && p.kind === 'unknown'" data-component="unknown"
         style="padding: var(--sd-space-md); color: var(--sd-text-dim)">
      Unknown component: {{ p.component }}
    </div>

    <div *ngIf="p && p.kind === 'component' && p.component === 'layout'"
         data-component="layout" [attr.data-variant]="variant"
         [ngStyle]="{ display: 'grid', 'grid-template-columns': columns, 'min-height': '100vh' }">
      <div *ngFor="let c of p.children" [attr.data-region]="c.key">
        <safe-renderer [plan]="c.plan" [onEvent]="onEvent"></safe-renderer>
      </div>
    </div>

    <div *ngIf="p && p.kind === 'component' && p.component === 'columns'"
         data-component="columns"
         [ngStyle]="{ display: 'grid', 'grid-template-columns': columns, gap: 'var(--sd-space-md)' }">
      <div *ngFor="let c of p.children" [attr.data-child]="c.key">
        <safe-renderer [plan]="c.plan" [onEvent]="onEvent"></safe-renderer>
      </div>
    </div>

    <ng-container *ngIf="p && p.kind === 'component' && p.component !== 'layout' && p.component !== 'columns'">
      <ng-container *ngComponentOutlet="impl; inputs: implInputs"></ng-container>
      <div *ngIf="p.childMode !== 'component' && p.children.length > 0" data-role="children">
        <safe-renderer *ngFor="let c of p.children" [plan]="c.plan" [onEvent]="onEvent"></safe-renderer>
      </div>
    </ng-container>
  `,
})
export class SafeRendererComponent implements OnChanges {
  @Input() config?: ConfigBase;
  @Input() plan?: RenderPlan;
  @Input() onEvent?: OnSafeEvent;

  p?: RenderPlan;
  impl: any;
  implInputs: Record<string, any> = {};
  columns = "1fr";
  variant?: string;

  ngOnChanges() {
    this.p = this.plan ?? (this.config ? buildRenderPlan(this.config, KNOWN) : undefined);
    if (!this.p) return;
    const handler = this.p.handler;
    const onEvent = this.onEvent;
    const stamped: OnSafeEvent | undefined = onEvent ? (event) => onEvent(stampHandler(event, handler)) : undefined;
    this.impl = LEAVES[this.p.component];
    this.implInputs = { config: this.p.config, onEvent: stamped };
    this.columns = (this.p.config.metadata?.["columns"] as string) ?? "1fr";
    this.variant = this.p.config.metadata?.["variant"] as string | undefined;
  }
}
