// svelte/4/SafeHierarchy.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { afterUpdate } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  afterUpdate(() => {
    root?.remove();
    container.innerHTML = '';
    root = buildComponent(config, onEvent);
    container.appendChild(root);
  });
  onDestroy(() => { root?.remove(); root = null; });
</script>

<div bind:this={container}></div>

// react/19/SafeHierarchy.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { buildComponent } from "../../utils/render";

interface SafeHierarchyProps {
  config: ConfigBase;
  onEvent?: OnSafeEvent;
}

export function SafeHierarchy({ config, onEvent }: SafeHierarchyProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    container.innerHTML = "";
    const root = buildComponent(config, onEvent);
    container.appendChild(root);
    return () => { root.remove(); };
  }, [config, onEvent]);

  return <div ref={containerRef} />;
}
