// svelte/4/SafeLayout.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { createSafeFireContext } from 'safecontracts';
  import { buildPayloadViaCli } from '../../utils/payload-delegate';
  import { createSafeLayout } from '../../builders/layout';
  import { buildComponent } from '../../utils/render';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  onMount(() => {
    const _ctx = createSafeFireContext(config, onEvent, buildPayloadViaCli);
    root = createSafeLayout(container, config, onEvent, buildComponent);
  });

  onDestroy(() => {
    root?.remove();
    root = null;
  });
</script>

<div bind:this={container}></div>

// react/19/SafeLayout.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { createSafeLayout } from "../../builders/layout";
import type { RenderChild } from "../../builders/layout";
import { createSafeFireContext } from "safecontracts";
import { buildPayloadViaCli } from "../../utils/payload-delegate";

interface SafeLayoutProps {
  config: ConfigBase;
  onEvent?: OnSafeEvent;
  renderChild?: RenderChild;
}

export function SafeLayout({ config, onEvent, renderChild }: SafeLayoutProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    const _ctx = createSafeFireContext(config, onEvent, buildPayloadViaCli);
    const root = createSafeLayout(container, config, onEvent, renderChild);
    return () => { root.remove(); };
  }, [config, onEvent, renderChild]);

  return <div ref={containerRef} />;
}
