// react/18/SafeScene.tsx
import { useRef, useEffect, useCallback } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { createSafeScene } from "../../builders/scene";

interface SafeSceneProps {
  config: ConfigBase;
  onEvent?: OnSafeEvent;
  renderChild?: (container: HTMLElement, child: ConfigBase, onEvent?: OnSafeEvent) => void;
}

export const SafeScene = ({ config, onEvent, renderChild }: SafeSceneProps) => {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    const root = createSafeScene(container, config, onEvent, renderChild);
    return () => { root.remove(); };
  }, [config, onEvent, renderChild]);

  return <div ref={containerRef} />;
};

// svelte/5/SafeScene.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { createSafeScene } from '../../builders/scene';

  let { config, onEvent }: { config: ConfigBase; onEvent?: OnSafeEvent } = $props();

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  $effect(() => {
    container.innerHTML = '';
    root = createSafeScene(container, config, onEvent);
    return () => { root?.remove(); root = null; };
  });
</script>

<div bind:this={container}></div>
