// react/18/SafeStoryFlow.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { buildComponent } from "../../utils/render";

interface SafeStoryFlowProps {
  config: ConfigBase;
  onEvent?: OnSafeEvent;
}

export function SafeStoryFlow({ config, onEvent }: SafeStoryFlowProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    container.innerHTML = "";
    const root = buildComponent(config, onEvent);
    container.appendChild(root);
    return () => { root.remove(); };
  }, [config, onEvent]);

  return <div ref={containerRef} />;
}

// svelte/5/SafeStoryFlow.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';

  let { config, onEvent }: { config: ConfigBase; onEvent?: OnSafeEvent } = $props();

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  $effect(() => {
    container.innerHTML = '';
    root = buildComponent(config, onEvent);
    container.appendChild(root);
    return () => { root?.remove(); root = null; };
  });
</script>

<div bind:this={container}></div>
