// vue/3/SafeRenderer.vue
<script setup lang="ts">
/**
 * SafeRenderer (vue/3) — mechanical translator of the contract's RenderPlan.
 * The walk (component resolution, handler stamping, child modes, unknown
 * fail-visibly) is decided by buildRenderPlan in safecontracts. This file
 * maps plan.component → the Vue implementation and recurses. Containers
 * (layout/columns) render natively here so children land inside regions —
 * same approach as react's SafeLayout.
 */
import { computed } from "vue";
import type { ConfigBase, OnSafeEvent, RenderPlan } from "safecontracts";
import { buildRenderPlan, stampHandler } from "safecontracts";
import SafeCard from "./SafeCard.vue";
import SafeButton from "./SafeButton.vue";
import SafeTable from "./SafeTable.vue";
import SafeTree from "./SafeTree.vue";
import SafeSheet from "./SafeSheet.vue";
import SafeChart from "./SafeChart.vue";
import SafeHeatmap from "./SafeHeatmap.vue";
import SafeGauge from "./SafeGauge.vue";
import SafeFunnel from "./SafeFunnel.vue";
import SafeFlow from "./SafeFlow.vue";
import SafeHierarchy from "./SafeHierarchy.vue";
import SafeTimeline from "./SafeTimeline.vue";
import SafeMap from "./SafeMap.vue";
import SafeCalendar from "./SafeCalendar.vue";
import SafeToggle from "./SafeToggle.vue";
import SafeWeek from "./SafeWeek.vue";
import SafeChat from "./SafeChat.vue";
import SafeTabs from "./SafeTabs.vue";
import SafeCallout from "./SafeCallout.vue";
import SafeDragDrop from "./SafeDragDrop.vue";
import SafeGrid from "./SafeGrid.vue";
import SafeInput from "./SafeInput.vue";
import SafeList from "./SafeList.vue";
import SafePicker from "./SafePicker.vue";
import SafeNav from "./SafeNav.vue";

const LEAVES: Record<string, any> = {
  card: SafeCard, button: SafeButton, table: SafeTable, tree: SafeTree,
  sheet: SafeSheet, chart: SafeChart, heatmap: SafeHeatmap, gauge: SafeGauge,
  funnel: SafeFunnel, flow: SafeFlow, hierarchy: SafeHierarchy,
  timeline: SafeTimeline, map: SafeMap, calendar: SafeCalendar,
  toggle: SafeToggle, week: SafeWeek, chat: SafeChat, tabs: SafeTabs,
  callout: SafeCallout, "drag-drop": SafeDragDrop, grid: SafeGrid,
  input: SafeInput, list: SafeList, picker: SafePicker, nav: SafeNav,
};
const KNOWN = new Set([...Object.keys(LEAVES), "layout", "columns"]);

const props = defineProps<{ config?: ConfigBase; plan?: RenderPlan; onEvent?: OnSafeEvent }>();

const plan = computed<RenderPlan>(() => props.plan ?? buildRenderPlan(props.config!, KNOWN));

const stamped = computed<OnSafeEvent | undefined>(() => {
  const handler = plan.value.handler;
  const onEvent = props.onEvent;
  if (!onEvent) return undefined;
  return (event) => onEvent(stampHandler(event, handler));
});

const impl = computed(() => LEAVES[plan.value.component]);

const gridStyle = computed(() => {
  const m = plan.value.config.metadata ?? {};
  const columns = (m.columns as string) ?? "1fr";
  return plan.value.component === "layout"
    ? { display: "grid", gridTemplateColumns: columns, minHeight: "100vh" }
    : { display: "grid", gridTemplateColumns: columns, gap: "var(--sd-space-md)" };
});
</script>

<template>
  <div v-if="plan.kind === 'unknown'" data-component="unknown" style="padding: var(--sd-space-md); color: var(--sd-text-dim)">
    Unknown component: {{ plan.component }}
  </div>

  <div v-else-if="plan.component === 'layout'" data-component="layout" :data-variant="plan.config.metadata?.variant" :style="gridStyle">
    <div v-for="c in plan.children" :key="c.key" :data-region="c.key">
      <SafeRenderer :plan="c.plan" :onEvent="props.onEvent" />
    </div>
  </div>

  <div v-else-if="plan.component === 'columns'" data-component="columns" :style="gridStyle">
    <div v-for="c in plan.children" :key="c.key" :data-child="c.key">
      <SafeRenderer :plan="c.plan" :onEvent="props.onEvent" />
    </div>
  </div>

  <template v-else>
    <component :is="impl" :config="plan.config" :onEvent="stamped" />
    <div v-if="plan.childMode !== 'component' && plan.children.length > 0" data-role="children">
      <SafeRenderer v-for="c in plan.children" :key="c.key" :plan="c.plan" :onEvent="props.onEvent" />
    </div>
  </template>
</template>

<script lang="ts">
export default { name: "SafeRenderer" };
</script>

// svelte/5/SafeRenderer.svelte
<script lang="ts">
  /**
   * SafeRenderer (svelte/5) — mechanical translator of the contract's
   * RenderPlan. Same walk as every framework (buildRenderPlan in
   * safecontracts); svelte 5 runes translation.
   */
  import SafeRenderer from "./SafeRenderer.svelte";
  import type { ConfigBase, OnSafeEvent, RenderPlan } from "safecontracts";
  import { buildRenderPlan, stampHandler } from "safecontracts";
  import SafeCard from "./SafeCard.svelte";
  import SafeButton from "./SafeButton.svelte";
  import SafeTable from "./SafeTable.svelte";
  import SafeTree from "./SafeTree.svelte";
  import SafeSheet from "./SafeSheet.svelte";
  import SafeChart from "./SafeChart.svelte";
  import SafeHeatmap from "./SafeHeatmap.svelte";
  import SafeGauge from "./SafeGauge.svelte";
  import SafeFunnel from "./SafeFunnel.svelte";
  import SafeFlow from "./SafeFlow.svelte";
  import SafeHierarchy from "./SafeHierarchy.svelte";
  import SafeTimeline from "./SafeTimeline.svelte";
  import SafeMap from "./SafeMap.svelte";
  import SafeCalendar from "./SafeCalendar.svelte";
  import SafeToggle from "./SafeToggle.svelte";
  import SafeWeek from "./SafeWeek.svelte";
  import SafeChat from "./SafeChat.svelte";
  import SafeTabs from "./SafeTabs.svelte";
  import SafeCallout from "./SafeCallout.svelte";
  import SafeDragDrop from "./SafeDragDrop.svelte";
  import SafeGrid from "./SafeGrid.svelte";
  import SafeInput from "./SafeInput.svelte";
  import SafeList from "./SafeList.svelte";
  import SafePicker from "./SafePicker.svelte";
  import SafeNav from "./SafeNav.svelte";

  const LEAVES: Record<string, any> = {
    card: SafeCard, button: SafeButton, table: SafeTable, tree: SafeTree,
    sheet: SafeSheet, chart: SafeChart, heatmap: SafeHeatmap, gauge: SafeGauge,
    funnel: SafeFunnel, flow: SafeFlow, hierarchy: SafeHierarchy,
    timeline: SafeTimeline, map: SafeMap, calendar: SafeCalendar,
    toggle: SafeToggle, week: SafeWeek, chat: SafeChat, tabs: SafeTabs,
    callout: SafeCallout, "drag-drop": SafeDragDrop, grid: SafeGrid,
    input: SafeInput, list: SafeList, picker: SafePicker, nav: SafeNav,
  };
  const KNOWN = new Set([...Object.keys(LEAVES), "layout", "columns"]);

  let { config, plan, onEvent }: { config?: ConfigBase; plan?: RenderPlan; onEvent?: OnSafeEvent } = $props();

  const p: RenderPlan = $derived(plan ?? buildRenderPlan(config!, KNOWN));
  const stamped: OnSafeEvent | undefined = $derived(
    onEvent ? (event) => onEvent!(stampHandler(event, p.handler)) : undefined
  );
  const columns: string = $derived((p.config.metadata?.columns as string) ?? "1fr");
</script>

{#if p.kind === "unknown"}
  <div data-component="unknown" style="padding: var(--sd-space-md); color: var(--sd-text-dim)">
    Unknown component: {p.component}
  </div>
{:else if p.component === "layout"}
  <div data-component="layout" data-variant={p.config.metadata?.variant} style="display:grid; grid-template-columns:{columns}; min-height:100vh">
    {#each p.children as c (c.key)}
      <div data-region={c.key}><SafeRenderer plan={c.plan} {onEvent} /></div>
    {/each}
  </div>
{:else if p.component === "columns"}
  <div data-component="columns" style="display:grid; grid-template-columns:{columns}; gap:var(--sd-space-md)">
    {#each p.children as c (c.key)}
      <div data-child={c.key}><SafeRenderer plan={c.plan} {onEvent} /></div>
    {/each}
  </div>
{:else}
  {@const Impl = LEAVES[p.component]}
  <Impl config={p.config} onEvent={stamped} />
  {#if p.childMode !== "component" && p.children.length > 0}
    <div data-role="children">
      {#each p.children as c (c.key)}
        <SafeRenderer plan={c.plan} {onEvent} />
      {/each}
    </div>
  {/if}
{/if}
