// vue/2/SafeBriefing.vue
<script lang="ts">
import { buildComponent } from '../../utils/render';

export default {
  name: 'SafeBriefing',
  props: { config: { type: Object, required: true }, onEvent: { type: Function, default: undefined } },
  mounted() {
    const root = buildComponent(this.config as any, this.onEvent as any);
    (this.$refs.container as HTMLElement).appendChild(root);
    (this as any)._root = root;
  },
  beforeDestroy() { (this as any)._root?.remove(); },
};
</script>
<template><div ref="container"></div></template>

// svelte/5/SafeBriefing.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';

  let { config, onEvent }: { config: ConfigBase; onEvent?: OnSafeEvent } = $props();
  let container: HTMLElement;
  let root: HTMLElement | null = null;

  $effect(() => {
    container.innerHTML = '';
    root = buildComponent(config, onEvent);
    container.appendChild(root);
    return () => { root?.remove(); root = null; };
  });
</script>
<div bind:this={container}></div>
