// svelte/4/SafeTable.svelte
<!--
  SafeTable — Svelte 4 table component.
  Outputs data-* attributes for intent. No hardcoded CSS.
-->
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
</script>

<div
  data-component="table"
  data-variant={config.metadata.variant}
  data-spacing={config.metadata.spacing}
  data-header-style={config.metadata.headerStyle}
  data-row-divider={config.metadata.rowDivider}
  data-row-numbers={config.metadata.rowNumbers}
  data-truncate={config.metadata.truncate}
  data-column-lines={config.metadata.columnLines}
  data-header-divider={config.metadata.headerDivider}
  data-zebra={config.metadata.zebra}
  data-selectable={config.metadata.selectable}
>
  <div data-role="scroll"><table><thead data-role="thead"><tr data-role="header-row"><th>Column</th><th>Value</th></tr></thead><tbody data-role="tbody"><tr data-role="row"><td data-role="cell">Sample</td><td data-role="cell">Data</td></tr></tbody></table></div>
</div>

// vue/2/SafeTable.vue
<!--
  SafeTable — Vue 2 table component.
  Outputs data-* attributes for intent. No hardcoded CSS.
-->
<script lang="ts">
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { defineComponent, type PropType } from 'vue';
export default defineComponent({
  name: 'SafeTable',
  props: {
    config: { type: Object as PropType<ConfigBase>, required: true },
    onEvent: { type: Function as PropType<OnSafeEvent>, default: undefined },
  },
});
</script>

<template>
  <div
    data-component="table"
    :data-variant="config.metadata.variant"
    :data-spacing="config.metadata.spacing"
    :data-header-style="config.metadata.headerStyle"
    :data-row-divider="config.metadata.rowDivider"
    :data-row-numbers="config.metadata.rowNumbers"
    :data-truncate="config.metadata.truncate"
    :data-column-lines="config.metadata.columnLines"
    :data-header-divider="config.metadata.headerDivider"
    :data-zebra="config.metadata.zebra"
    :data-selectable="config.metadata.selectable"
  >
      <div data-role="scroll"><table><thead data-role="thead"><tr data-role="header-row"><th>Column</th><th>Value</th></tr></thead><tbody data-role="tbody"><tr data-role="row"><td data-role="cell">Sample</td><td data-role="cell">Data</td></tr></tbody></table></div>
  </div>
</template>
