// react/19/SafeSkillUp.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { buildComponent } from "../../utils/render";
interface SafeSkillUpProps { config: ConfigBase; onEvent?: OnSafeEvent; }
export function SafeSkillUp({ config, onEvent }: SafeSkillUpProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const c = containerRef.current; if (!c) return; c.innerHTML = ""; const r = buildComponent(config, onEvent); c.appendChild(r); return () => { r.remove(); }; }, [config, onEvent]);
  return <div ref={containerRef} />;
}

// vue/2/SafeSkillUp.vue
<script lang="ts">
import { buildComponent } from '../../utils/render';
export default {
  name: 'SafeSkillUp',
  props: { config: { type: Object, required: true }, onEvent: { type: Function, default: undefined } },
  mounted() { const r = buildComponent(this.config as any, this.onEvent as any); (this.$refs.container as HTMLElement).appendChild(r); (this as any)._root = r; },
  beforeDestroy() { (this as any)._root?.remove(); },
};
</script>
<template><div ref="container"></div></template>
