// svelte/5/SafeDispatch.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';
  let { config, onEvent }: { config: ConfigBase; onEvent?: OnSafeEvent } = $props();
  let container: HTMLElement;
  let root: HTMLElement | null = null;
  $effect(() => { container.innerHTML = ''; root = buildComponent(config, onEvent); container.appendChild(root); return () => { root?.remove(); root = null; }; });
</script>
<div bind:this={container}></div>

// vue/2/SafeDispatch.vue
<script lang="ts">
import { buildComponent } from '../../utils/render';
export default {
  name: 'SafeDispatch',
  props: { config: { type: Object, required: true }, onEvent: { type: Function, default: undefined } },
  mounted() { const r = buildComponent(this.config as any, this.onEvent as any); (this.$refs.container as HTMLElement).appendChild(r); (this as any)._root = r; },
  beforeDestroy() { (this as any)._root?.remove(); },
};
</script>
<template><div ref="container"></div></template>
