// svelte/4/SafeInput.svelte
<!--
  SafeInput — Svelte 4 input component.
  Renders via shared-mapping input builder (./input) — identical across
  frameworks. Structure + data-* only. No hardcoded CSS.
-->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { createSafeInput } from './input';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  onMount(() => {
    root = createSafeInput(container, config, onEvent);
  });

  onDestroy(() => {
    root?.remove();
    root = null;
  });
</script>

<div bind:this={container}></div>

// vue/2/SafeInput.vue
<!--
  SafeInput — Vue 2 input component.
  Renders via shared-mapping input builder (./input) — identical across
  frameworks. Structure + data-* only. No hardcoded CSS.
-->
<script lang="ts">
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { defineComponent, type PropType } from 'vue';
import { createSafeInput } from './input';

export default defineComponent({
  name: 'SafeInput',
  props: {
    config: { type: Object as PropType<ConfigBase>, required: true },
    onEvent: { type: Function as PropType<OnSafeEvent>, default: undefined },
  },
  data() {
    return { root: null as HTMLElement | null };
  },
  mounted() {
    const el = this.$refs.inputContainer as HTMLElement;
    if (el) this.root = createSafeInput(el, this.config, this.onEvent);
  },
  beforeDestroy() {
    this.root?.remove();
    this.root = null;
  },
});
</script>

<template>
  <div ref="inputContainer"></div>
</template>
