// vue/3/SafeFlow.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { renderSafeFlow, flowData } from '../../builders/flow';

const props = defineProps<{ config: ConfigBase; onEvent?: OnSafeEvent }>();
const svgRef = ref<SVGSVGElement | null>(null);

onMounted(() => {
  if (svgRef.value) renderSafeFlow(svgRef.value, props.config, flowData(props.config), props.onEvent);
});
</script>

<template>
  <div>
    <div v-if="config.metadata.title" data-role="title">{{ config.metadata.title }}</div>
    <svg ref="svgRef" data-flow-svg></svg>
  </div>
</template>

// react/18/SafeFlow.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { renderSafeFlow, flowData } from "../../builders/flow";

/*----------------------------------------------------------------------------------------------------
 *
 * Properties
 *
 ----------------------------------------------------------------------------------------------------*/

interface SafeFlowProps {
  config: ConfigBase;
  onEvent?: OnSafeEvent;
}

/*----------------------------------------------------------------------------------------------------
 *
 * Helpers
 *
 ----------------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------------
 *
 * Implementation
 *
 ----------------------------------------------------------------------------------------------------*/

export function SafeFlow({ config, onEvent }: SafeFlowProps) {
  const { metadata } = config;
  const svgRef = useRef<SVGSVGElement>(null);

  useEffect(() => {
    if (!svgRef.current) return;
    renderSafeFlow(svgRef.current, config, flowData(config), onEvent);
  }, [config, onEvent]);

  return (
    <div>
      {metadata.title != null && <div data-role="title">{metadata.title as string}</div>}
      <svg ref={svgRef} data-flow-svg />
    </div>
  );
}
