// svelte/5/SafeDispatch.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';
  let { config, onEvent }: { config: ConfigBase; onEvent?: OnSafeEvent } = $props();
  let container: HTMLElement;
  let root: HTMLElement | null = null;
  $effect(() => { container.innerHTML = ''; root = buildComponent(config, onEvent); container.appendChild(root); return () => { root?.remove(); root = null; }; });
</script>
<div bind:this={container}></div>

// react/18/SafeDispatch.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { buildComponent } from "../../utils/render";
interface SafeDispatchProps { config: ConfigBase; onEvent?: OnSafeEvent; }
export function SafeDispatch({ config, onEvent }: SafeDispatchProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const c = containerRef.current; if (!c) return; c.innerHTML = ""; const r = buildComponent(config, onEvent); c.appendChild(r); return () => { r.remove(); }; }, [config, onEvent]);
  return <div ref={containerRef} />;
}
