// vue/2/SafeCallout.vue
<!--
  SafeCallout — Vue 2 callout component.
  Implements callout contract from safecontracts.
  Outputs data-* attributes for intent. No hardcoded CSS.
-->
<script lang="ts">
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { defineComponent, type PropType } from 'vue';

export default defineComponent({
  name: 'SafeCallout',
  props: {
    config: { type: Object as PropType<ConfigBase>, required: true },
    onEvent: { type: Function as PropType<OnSafeEvent>, default: undefined },
  },
});
</script>

<template>
  <div
    data-component="callout"
    :data-variant="config.metadata.variant"
    :data-position="config.metadata.position"
  >
    <slot />
  </div>
</template>

// svelte/4/SafeCallout.svelte
<!--
  SafeCallout — Svelte 5 callout component.
  Implements callout contract from safecontracts.
  Outputs data-* attributes for intent. No hardcoded CSS.
-->
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
</script>

<div
  data-component="callout"
  data-variant={config.metadata.variant}
  data-position={config.metadata.position}
>
  <slot />
</div>
