// vue/3/SafeFlow.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { renderSafeFlow, flowData } from '../../builders/flow';

const props = defineProps<{ config: ConfigBase; onEvent?: OnSafeEvent }>();
const svgRef = ref<SVGSVGElement | null>(null);

onMounted(() => {
  if (svgRef.value) renderSafeFlow(svgRef.value, props.config, flowData(props.config), props.onEvent);
});
</script>

<template>
  <div>
    <div v-if="config.metadata.title" data-role="title">{{ config.metadata.title }}</div>
    <svg ref="svgRef" data-flow-svg></svg>
  </div>
</template>

// svelte/4/SafeFlow.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { renderSafeFlow, flowData } from '../../builders/flow';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let svg: SVGSVGElement;

  onMount(() => {
    renderSafeFlow(svg, config, flowData(config), onEvent);
  });
</script>

<div>
  {#if config.metadata.title}<div data-role="title">{config.metadata.title}</div>{/if}
  <svg bind:this={svg} data-flow-svg></svg>
</div>
