// vue/3/SafeHierarchy.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { createSafeFireContext } from 'safecontracts';
import { buildPayloadViaCli } from '../../utils/payload-delegate';
import { createSafeHierarchy } from '../../builders/hierarchy';

const props = defineProps<{ config: ConfigBase; onEvent?: OnSafeEvent }>();
const containerRef = ref<HTMLElement | null>(null);
let root: HTMLElement | null = null;

onMounted(() => {
  if (containerRef.value) {
    const _ctx = createSafeFireContext(props.config, props.onEvent, buildPayloadViaCli);
    root = createSafeHierarchy(containerRef.value, props.config, _ctx);
  }
});
onBeforeUnmount(() => { root?.remove(); root = null; });
</script>

<template>
  <div ref="containerRef"></div>
</template>

// svelte/4/SafeHierarchy.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { afterUpdate } from 'svelte';
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { createSafeFireContext } from 'safecontracts';
  import { buildPayloadViaCli } from '../../utils/payload-delegate';
  import { createSafeHierarchy } from '../../builders/hierarchy';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;

  let container: HTMLElement;
  let root: HTMLElement | null = null;

  afterUpdate(() => {
    root?.remove();
    container.innerHTML = '';
    const _ctx = createSafeFireContext(config, onEvent, buildPayloadViaCli);
    root = createSafeHierarchy(container, config, _ctx);
  });
  onDestroy(() => { root?.remove(); root = null; });
</script>

<div bind:this={container}></div>
