// angular/21/SafePlan.ts
import { Component, Input, ElementRef, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';
import { buildComponent } from '../../utils/render';

@Component({ selector: 'safe-plan', standalone: true, template: `<div #planContainer></div>` })
export class SafePlanComponent implements AfterViewInit, OnDestroy {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
  @ViewChild('planContainer') containerRef!: ElementRef<HTMLElement>;
  private root: HTMLElement | null = null;
  ngAfterViewInit() { this.root = buildComponent(this.config, this.onEvent); this.containerRef.nativeElement.appendChild(this.root); }
  ngOnDestroy() { this.root?.remove(); this.root = null; }
}

// svelte/4/SafePlan.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';
  import { onMount, onDestroy } from 'svelte';
  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
  let container: HTMLElement;
  let root: HTMLElement | null = null;
  onMount(() => { root = buildComponent(config, onEvent); container.appendChild(root); });
  onDestroy(() => { root?.remove(); root = null; });
</script>
<div bind:this={container}></div>
