// angular/21/SafeFunnel.ts
/**
 * SafeFunnel — Angular funnel component.
 * Implements funnel contract from safecontracts.
 * Outputs data-* attributes for intent. No hardcoded CSS.
 */
import { Component, Input } from '@angular/core';
import type { ConfigBase, OnSafeEvent } from 'safecontracts';

@Component({
  selector: 'safe-funnel',
  standalone: true,
  template: `
    <div style="display:flex;flex-direction:column;gap:4px;padding:8px">
      <div style="background:var(--sd-accent,#3b82f6);color:white;padding:8px;text-align:center;border-radius:4px;width:100%">Leads: 100</div>
      <div style="background:var(--sd-accent,#3b82f6);color:white;padding:8px;text-align:center;border-radius:4px;width:75%;margin:0 auto">Qualified: 75</div>
      <div style="background:var(--sd-accent,#3b82f6);color:white;padding:8px;text-align:center;border-radius:4px;width:50%;margin:0 auto">Won: 50</div>
    </div>
  `,
  host: {
    '[attr.data-component]': "'funnel'",
    '[attr.data-variant]': 'config.metadata.variant'
  }
})
export class SafeFunnelComponent {
  @Input() config!: ConfigBase;
  @Input() onEvent?: OnSafeEvent;
}

// svelte/4/SafeFunnel.svelte
<!--
  SafeFunnel — Svelte 4 funnel component.
  Outputs data-* attributes for intent. No hardcoded CSS.
-->
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
</script>

<div
  data-component="funnel"
  data-variant={config.metadata.variant}
>
  <div style="display:flex;flex-direction:column;gap:4px;padding:8px"><div style="background:var(--sd-accent,#3b82f6);color:white;padding:8px;text-align:center;border-radius:4px;width:100%">Leads: 100</div><div style="background:var(--sd-accent,#3b82f6);color:white;padding:8px;text-align:center;border-radius:4px;width:75%;margin:0 auto">Qualified: 75</div><div style="background:var(--sd-accent,#3b82f6);color:white;padding:8px;text-align:center;border-radius:4px;width:50%;margin:0 auto">Won: 50</div></div>
</div>
