// vue/2/SafeParser.vue
<script lang="ts">
import { buildComponent } from '../../utils/render';

export default {
  name: 'SafeParser',
  props: { config: { type: Object, required: true }, onEvent: { type: Function, default: undefined } },
  mounted() {
    const root = buildComponent(this.config as any, this.onEvent as any);
    (this.$refs.container as HTMLElement).appendChild(root);
    (this as any)._root = root;
  },
  beforeDestroy() { (this as any)._root?.remove(); },
};
</script>
<template><div ref="container"></div></template>

// svelte/4/SafeParser.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';
  import { onMount, onDestroy } from 'svelte';

  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
  let container: HTMLElement;
  let root: HTMLElement | null = null;

  onMount(() => {
    root = buildComponent(config, onEvent);
    container.appendChild(root);
  });
  onDestroy(() => { root?.remove(); root = null; });
</script>
<div bind:this={container}></div>
