// react/18/SafePlan.tsx
import { useRef, useEffect } from "react";
import type { ConfigBase, OnSafeEvent } from "safecontracts";
import { buildComponent } from "../../utils/render";

interface SafePlanProps { config: ConfigBase; onEvent?: OnSafeEvent; }

export function SafePlan({ config, onEvent }: SafePlanProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    container.innerHTML = "";
    const root = buildComponent(config, onEvent);
    container.appendChild(root);
    return () => { root.remove(); };
  }, [config, onEvent]);
  return <div ref={containerRef} />;
}

// svelte/4/SafePlan.svelte
<script lang="ts">
  import type { ConfigBase, OnSafeEvent } from 'safecontracts';
  import { buildComponent } from '../../utils/render';
  import { onMount, onDestroy } from 'svelte';
  export let config: ConfigBase;
  export let onEvent: OnSafeEvent | undefined = undefined;
  let container: HTMLElement;
  let root: HTMLElement | null = null;
  onMount(() => { root = buildComponent(config, onEvent); container.appendChild(root); });
  onDestroy(() => { root?.remove(); root = null; });
</script>
<div bind:this={container}></div>
